package ddev

import "testing"

// TestIgnoreMarkerBreaksTheFeedbackLoop. Whatever registers the variant
// hostnames has to write them into a .ddev/config.*.yaml, or mkcert issues no
// SAN for them and the browser gets a TLS interstitial instead of a site. That
// file is then input to the next run: the variants come back as canonical hosts,
// get variants of their own, and additional_hostnames grows without bound.
//
// Observed before the marker existed — three runs of `ddev hostshift init` in
// one worktree took additional_hostnames from 4 entries to 16 and produced
// third--my-slug--feature-cool-thing--site.ddev.site. Rerunning after a branch
// rename is the normal thing to do, and the generated file's own header invites
// it ("rerun to update").
func TestIgnoreMarkerBreaksTheFeedbackLoop(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, ".ddev/config.yaml", "name: site\nadditional_hostnames:\n  - blog\n")
	write(t, dir, ".ddev/config.hostshift.local.yaml",
		"# generated by `ddev hostshift init` — hostshift:ignore\n"+
			"additional_hostnames:\n  - site\n  - blog\n  - wt-a--site\n  - wt-a--blog\n")

	p, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, h := range p.Hosts {
		if h == "wt-a--site.ddev.site" || h == "wt-a--blog.ddev.site" {
			t.Fatalf("read back a hostname it generated itself: %v", p.Hosts)
		}
	}
	if len(p.Hosts) != 2 {
		t.Errorf("hosts = %v; want the two the project actually declares", p.Hosts)
	}
}

// An override file without the marker is still merged, which is the behaviour a
// worktree depends on to give itself a project name of its own.
func TestOverridesWithoutTheMarkerAreStillRead(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, ".ddev/config.yaml", "name: site\n")
	write(t, dir, ".ddev/config.worktree.local.yaml", "name: site-wt-a\nadditional_hostnames:\n  - extra\n")

	p, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if p.Name != "site-wt-a" {
		t.Errorf("name = %q; want site-wt-a", p.Name)
	}
	if len(p.Hosts) != 2 {
		t.Errorf("hosts = %v; want two", p.Hosts)
	}
}
