package rewrite

import (
	"bufio"
	"compress/gzip"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/generoi/hostshift/internal/origin"
)

// A differential test against the URL parser browsers actually run.
//
// Five audit rounds in a row found a test-28 leak, and every one was the same
// mistake in a different place: the byte model saying one thing and the WHATWG
// URL parser saying another. Fuzzing the engine's invariants found none of them,
// because the invariants held — what was wrong was the *model*, and a property
// test cannot discover a model it shares with the code under test.
//
// So the model gets an oracle. testdata/url-shapes.tsv is generated by
// test/gen-url-corpus.js from Node's URL, which is ada, the parser Chrome ships.
// Each row is a URL spelling and the host a browser resolves it to against the
// variant origin as base. The contract is then exactly test 28 in both
// directions:
//
//   - the browser resolves it to the canonical  ⇒  hostshift must rewrite it
//   - the browser resolves it anywhere else     ⇒  hostshift must not touch it
//
// The second half is the one that keeps a fix honest: every round so far that
// widened the matcher risked rewriting something that was already correct.

const (
	oracleCanonical = "www.example.fi"
	oracleVariant   = "wt-a--example.ddev.site"
)

type urlShape struct {
	base      string // the document's scheme: "https" or "http"
	candidate string
	resolved  string
}

func loadShapes(t *testing.T) []urlShape {
	t.Helper()
	// Gzipped: 137,500 rows is 7 MB of text and 200 KB compressed, and the
	// coverage is the point — a smaller corpus would mean choosing in advance
	// which shapes matter, which is the judgement that has been wrong five
	// rounds running.
	f, err := os.Open("../../testdata/url-shapes.tsv.gz")
	if err != nil {
		t.Fatalf("%v (regenerate: node test/gen-url-corpus.js | gzip -9 > testdata/url-shapes.tsv.gz)", err)
	}
	defer f.Close()
	zr, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}
	defer zr.Close()

	var out []urlShape
	sc := bufio.NewScanner(zr)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		first := strings.IndexByte(line, '\t')
		last := strings.LastIndexByte(line, '\t')
		if first < 0 || last <= first {
			continue
		}
		var cand string
		if err := json.Unmarshal([]byte(line[first+1:last]), &cand); err != nil {
			t.Fatalf("corpus line %q: %v", line, err)
		}
		out = append(out, urlShape{
			base:      line[:first],
			candidate: cand,
			resolved:  line[last+1:],
		})
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if len(out) == 0 {
		t.Fatal("empty corpus")
	}
	return out
}

// oracleMatcher builds the map for a document served on the given scheme. The
// variant's scheme *is* the document's scheme — the page is served at the
// variant origin — and that is what decides whether `https:host` is an authority
// or a path, so a corpus with one base only ever exercised half the rule.
func oracleMatcher(t *testing.T, base string) *origin.Matcher {
	t.Helper()
	if base == "" {
		base = "https"
	}
	m, err := origin.NewMatcher([]origin.Pair{{
		Canonical: origin.MustParse("https://" + oracleCanonical),
		Variant:   origin.MustParse(base + "://" + oracleVariant),
	}})
	if err != nil {
		t.Fatal(err)
	}
	return m
}

// surfaces wraps a URL the way each of the rewriter's surfaces would carry it.
// A leak is a leak wherever the origin sits: §5.2 calls inline script and style
// Tier 1, and a comment or a text node is still read by scripts.
var surfaces = []struct {
	name       string
	cssEscapes bool
	wrap       func(string) string
}{
	{"href", false, func(u string) string { return `<a href="` + u + `">x</a>` }},
	{"src", false, func(u string) string { return `<img src="` + u + `">` }},
	{"data-attr", false, func(u string) string { return `<div data-large_image="` + u + `">x</div>` }},
	{"text", false, func(u string) string { return `<p>` + u + `</p>` }},
	{"inline script", false, func(u string) string { return `<script>fetch("` + u + `")</script>` }},
	// cssEscapes: on a style surface the CSS tokenizer runs first, so `\a` is a
	// newline escape rather than two literal bytes and the raw-URL oracle no
	// longer describes what a browser sees. Those candidates are skipped here;
	// TestCSSEscapesAreRewritten covers that path against a real browser.
	{"inline style", true, func(u string) string { return `<style>a{background:url(` + u + `)}</style>` }},
	{"comment", false, func(u string) string { return `<!-- ` + u + ` -->` }},
}

// knownRelativePortLimit is the one place hostshift and the parser disagree, and
// it is a deliberate limitation rather than an oversight.
//
// A scheme-relative `//host:443` names https://host:443 under an https document
// and http://host:443 under an http one. The byte matcher has no document to
// consult, so it resolves the reference under the *canonical's* scheme — which
// is right whenever the document and the canonical share a scheme, and that is
// every configuration the fleet has: DDEV serves https and the canonicals are
// https.
//
// Where it is wrong — an http-served variant, a scheme-relative reference, and
// an explicit port that is the other scheme's default — the error is a false
// positive on a URL that pointed at nothing (http://host:443), not a leak. The
// alternative is teaching the hot-path scanner which scheme the document is
// served on, which is a large change to buy a case with no reachable harm.
// Recorded here rather than quietly excluded, and in PLAN §5.5.
func knownRelativePortLimit(sh urlShape) bool {
	if sh.base != "http" || sh.candidate == "" {
		return false
	}
	if _, scheme := schemeLen([]byte(sh.candidate)); scheme != "" {
		return false
	}
	if !isSlashish(sh.candidate[0]) {
		return false
	}
	return strings.HasSuffix(sh.resolved, ":443")
}

func TestURLShapesAgainstBrowserOracle(t *testing.T) {
	shapes := loadShapes(t)
	byBase := map[string]*origin.Matcher{
		"https": oracleMatcher(t, "https"),
		"http":  oracleMatcher(t, "http"),
	}

	// The whole corpus on the surface most origins live on, then a deterministic
	// slice of it on every surface — a missed *surface* is how two of the last
	// three rounds' leaks survived, so the matrix matters as much as the shapes.
	run := func(t *testing.T, list []urlShape, only []int) {
		t.Helper()
		var leaked, falsePos int
		for _, sh := range list {
			for _, si := range only {
				s := surfaces[si]
				if s.cssEscapes && strings.ContainsRune(sh.candidate, '\\') {
					continue
				}
				if knownRelativePortLimit(sh) {
					continue
				}
				in := s.wrap(sh.candidate)
				out := rewriteHTML(t, byBase[sh.base], in, NewStats(false))

				// A trailing root dot names the same host in DNS, and PLAN §4.4
				// specifies absorbing it. The parser keeps it in `host`, so the
				// oracle has to be told the two are one origin.
				resolved := strings.TrimSuffix(sh.resolved, ".")
				if resolved == oracleCanonical {
					if !strings.Contains(out, oracleVariant) {
						leaked++
						if leaked <= 10 {
							t.Errorf("[%s] a browser resolves this to %s and it was not rewritten:\n in  %q\n out %q",
								s.name, oracleCanonical, sh.candidate, out)
						}
					}
					continue
				}
				// Resolves somewhere else, or the parser rejects it outright.
				// Either way nothing here points at production, so nothing may
				// change — this is the half that catches a widened matcher
				// rewriting what was already correct.
				if out != in {
					falsePos++
					if falsePos <= 10 {
						t.Errorf("[%s] a browser resolves this to %q, so it must not change:\n in  %q\n out %q",
							s.name, resolved, in, out)
					}
				}
			}
		}
		if leaked > 10 || falsePos > 10 {
			t.Errorf("%d leaks and %d false positives in total", leaked, falsePos)
		}
	}

	t.Run("every shape in an href", func(t *testing.T) {
		if testing.Short() {
			t.Skip("corpus sweep")
		}
		run(t, shapes, []int{0})
	})

	t.Run("a slice of shapes on every surface", func(t *testing.T) {
		var slice []urlShape
		for i := 0; i < len(shapes); i += 37 {
			slice = append(slice, shapes[i])
		}
		all := make([]int, len(surfaces))
		for i := range surfaces {
			all[i] = i
		}
		run(t, slice, all)
	})
}

// The response manufactures obfuscated variants — it splices only the host, so
// the wrapper survives — and the request direction has to reverse every one of
// them, or a form post writes a worktree-local hostname into the database §4.3
// says stays byte-identical to production.
// cssEscapeScheme rewrites `https://` as CSS writes it, so the forward pass has
// something to splice a host into in escaped form.
func cssEscapeScheme(u string) string {
	for _, s := range []string{"https://", "http://"} {
		if strings.HasPrefix(u, s) {
			return strings.TrimSuffix(s, "://") + `\3a \2f \2f ` + u[len(s):]
		}
	}
	return u
}

func TestOracleShapesRoundTrip(t *testing.T) {
	shapes := loadShapes(t)
	fwd := oracleMatcher(t, "https")
	rev, err := origin.NewMatcher([]origin.Pair{{
		Canonical: origin.MustParse("https://" + oracleVariant),
		Variant:   origin.MustParse("https://" + oracleCanonical),
	}})
	if err != nil {
		t.Fatal(err)
	}

	// Every surface, not just href. The forward direction splices in place, so
	// each surface's own encoding survives into what the browser is handed — and
	// round sixteen found the CSS one emitting `url(https\3a \2f \2f <variant>/x)`,
	// which nothing on the request path could read, so the *variant* hostname was
	// written into the database §4.3 says stays byte-identical to production.
	// That is the general rule this asserts: every spelling the forward direction
	// can emit, the reverse must be able to read.
	wrappers := []struct {
		name string
		wrap func(string) string
	}{
		{"href", func(u string) string { return `<a href="` + u + `">x</a>` }},
		{"style attribute", func(u string) string { return `<div style="background:url(` + u + `)">x</div>` }},
		{"style element", func(u string) string { return `<style>a{background:url(` + u + `)}</style>` }},
		{"inline script", func(u string) string { return `<script>fetch("` + u + `")</script>` }},
		{"text", func(u string) string { return `<p>` + u + `</p>` }},
		{"srcset", func(u string) string { return `<img srcset="` + u + ` 1x">` }},
		// CSS-escaped input, which is what makes the forward pass *emit* the
		// escaped spelling — the one round sixteen found the request path could
		// not read. Wrapping a plain URL in a style attribute is not enough: the
		// ordinary locator handles that and emits a plain variant.
		{"css-escaped style attribute", func(u string) string {
			return `<div style="background:url(` + cssEscapeScheme(u) + `)">x</div>`
		}},
		{"css-escaped style element", func(u string) string {
			return `<style>a{background:url(` + cssEscapeScheme(u) + `)}</style>`
		}},
	}

	var bad int
	for i, sh := range shapes {
		if i%37 != 0 || sh.base != "https" || strings.TrimSuffix(sh.resolved, ".") != oracleCanonical {
			continue
		}
		for _, w := range wrappers {
			served := rewriteHTML(t, fwd, w.wrap(sh.candidate), NewStats(false))
			// What the browser would send back: the rewritten value, through the
			// request direction.
			back := string(HostLeaks(rev, []byte(served), true))
			if strings.Contains(back, oracleVariant) {
				bad++
				if bad <= 10 {
					t.Errorf("[%s] a variant hostname survives the request direction:\n from %q\n sent %q\n back %q",
						w.name, sh.candidate, served, back)
				}
			}
		}
	}
	if bad > 10 {
		t.Errorf("%d shape/surface combinations did not round-trip", bad)
	}
}
